require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: "2.7.0"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  CountAsOne: ["hash", "array", "method_call"]
  Max: 14

Layout/IndentationStyle:
  IndentationWidth: 1
  EnforcedStyle: tabs

Layout/IndentationWidth:
  Width: 1

Style/Documentation:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Metrics/AbcSize:
  Max: 18.92
